name: n2_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.12.0
  boolean_selector: ^2.1.2
  characters: ^1.3.1
  clock: ^1.1.2
  collection: ^1.19.1
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1
  stack_trace: ^1.12.0
  string_scanner: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
